import { writeFile } from "node:fs/promises";
import { extname } from "node:path";
import type { Operation, Finding, MetricEvent } from "@shipwell/core";

export interface ExportData {
  operation: Operation;
  source: string;
  model: string;
  timestamp: string;
  findings: Finding[];
  metrics: MetricEvent[];
  summary: string | null;
  stats: {
    totalFindings: number;
    crossFileCount: number;
    duration: number;
    filesAnalyzed: number;
    tokensProcessed: number;
  };
}

const opLabels: Record<string, string> = {
  audit: "Security Audit",
  migrate: "Migration Plan",
  refactor: "Refactor Analysis",
  docs: "Documentation",
  upgrade: "Dependency Upgrade",
};

function severityLabel(sev?: string): string {
  if (!sev) return "INFO";
  return sev.toUpperCase();
}

export function exportMarkdown(data: ExportData): string {
  const lines: string[] = [];
  const title = `${opLabels[data.operation] || data.operation} Report`;

  lines.push(`# ${title}`);
  lines.push(`**Source:** ${data.source} | **Model:** ${data.model} | **Date:** ${data.timestamp}`);
  lines.push("");

  // Summary
  if (data.summary) {
    lines.push("## Summary");
    lines.push(data.summary);
    lines.push("");
  }

  // Findings table
  if (data.findings.length > 0) {
    lines.push(`## Findings (${data.findings.length})`);
    lines.push("| # | Severity | Title | Files | Cross-file |");
    lines.push("|---|----------|-------|-------|------------|");
    for (let i = 0; i < data.findings.length; i++) {
      const f = data.findings[i];
      const files = f.files.join(", ");
      const cross = f.crossFile ? "Yes" : "No";
      lines.push(`| ${i + 1} | ${severityLabel(f.severity)} | ${f.title} | ${files} | ${cross} |`);
    }
    lines.push("");

    // Detailed findings
    for (let i = 0; i < data.findings.length; i++) {
      const f = data.findings[i];
      lines.push(`### ${i + 1}. ${f.title}`);
      lines.push(`**Severity:** ${severityLabel(f.severity)} | **Files:** ${f.files.join(", ")}`);
      if (f.description) {
        lines.push(f.description);
      }
      if (f.diff) {
        lines.push("```diff");
        lines.push(f.diff);
        lines.push("```");
      }
      lines.push("");
    }
  }

  // Metrics
  if (data.metrics.length > 0) {
    lines.push("## Metrics");
    lines.push("| Metric | Before | After | Unit |");
    lines.push("|--------|--------|-------|------|");
    for (const m of data.metrics) {
      lines.push(`| ${m.label} | ${m.before} | ${m.after} | ${m.unit || ""} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("Generated by Shipwell \u00B7 shipwell.app");

  return lines.join("\n");
}

export function exportJson(data: ExportData): string {
  return JSON.stringify(data, null, 2);
}

export async function writeReport(data: ExportData, outputPath: string): Promise<void> {
  const ext = extname(outputPath).toLowerCase();
  const content = ext === ".json" ? exportJson(data) : exportMarkdown(data);
  await writeFile(outputPath, content, "utf-8");
}
